export const categoryConstant = {
    GET_ALL_CATEGORYPM_REQUEST: "GET_ALL_CATEGORYPM_REQUEST",
    GET_ALL_CATEGORYPM_SUCCESS: "GET_ALL_CATEGORYPM_SUCCESS",
    GET_ALL_CATEGORYPM_FAILURE: "GET_ALL_CATEGORYPM_FAILURE",
    GET_ALL_CATEGORY_REQUEST: "GET_ALL_CATEGORY_REQUEST",
    GET_ALL_CATEGORY_SUCCESS: "GET_ALL_CATEGORY_SUCCESS",
    GET_ALL_CATEGORY_FAILURE: "GET_ALL_CATEGORY_FAILURE",
    ADD_CATEGORY_REQUEST: "ADD_CATEGORY_REQUEST",
    ADD_CATEGORY_SUCCESS: "ADD_CATEGORY_SUCCESS",
    ADD_CATEGORY_FAILURE: "ADD_CATEGORY_FAILURE",
    UPDATE_CATEGORY_REQUEST: "UPDATE_CATEGORY_REQUEST",
    UPDATE_CATEGORY_SUCCESS: "UPDATE_CATEGORY_SUCCESS",
    UPDATE_CATEGORY_FAILURE: "UPDATE_CATEGORY_FAILURE",
    REMOVE_CATEGORY_REQUEST: "REMOVE_CATEGORY_REQUEST",
    REMOVE_CATEGORY_SUCCESS: "REMOVE_CATEGORY_SUCCESS",
    REMOVE_CATEGORY_FAILURE: "REMOVE_CATEGORY_FAILURE",
}

export const infoConstant = {
    GET_INFO_REQUEST: "GET_INFO_REQUEST",
    GET_INFO_SUCCESS: "GET_INFO_SUCCESS",
    GET_INFO_FAILURE: "GET_INFO_FAILURE",
    UPDATE_INFO_REQUEST: "UPDATE_INFO_REQUEST",
    UPDATE_INFO_SUCCESS: "UPDATE_INFO_SUCCESS",
    UPDATE_INFO_FAILURE: "UPDATE_INFO_FAILURE",
}

export const userConstant = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT_SUCCESS: 'LOUOUT_SUCCESS',
}

export const partyMemberConstant = {
    GET_ALL_PARTYMEMBER_REQUEST: "GET_ALL_PARTYMEMBER_REQUEST",
    GET_ALL_PARTYMEMBER_SUCCESS: "GET_ALL_PARTYMEMBER_SUCCESS",
    GET_ALL_PARTYMEMBER_FAILURE: "GET_ALL_PARTYMEMBER_FAILURE",
    ADD_PARTYMEMBER_REQUEST: "ADD_PARTYMEMBER_REQUEST",
    ADD_PARTYMEMBER_SUCCESS: "ADD_PARTYMEMBER_SUCCESS",
    ADD_PARTYMEMBER_FAILURE: "ADD_PARTYMEMBER_FAILURE",
    UPDATE_PARTYMEMBER_REQUEST: "UPDATE_PARTYMEMBER_REQUEST",
    UPDATE_PARTYMEMBER_SUCCESS: "UPDATE_PARTYMEMBER_SUCCESS",
    UPDATE_PARTYMEMBER_FAILURE: "UPDATE_PARTYMEMBER_FAILURE",
    REMOVE_PARTYMEMBER_REQUEST: "REMOVE_PARTYMEMBER_REQUEST",
    REMOVE_PARTYMEMBER_SUCCESS: "REMOVE_PARTYMEMBER_SUCCESS",
    REMOVE_PARTYMEMBER_FAILURE: "REMOVE_PARTYMEMBER_FAILURE",
}