export const categoryConstant = {
    GET_ALL_CATEGORY_REQUEST: "GET_ALL_CATEGORY_REQUEST",
    GET_ALL_CATEGORY_SUCCESS: "GET_ALL_CATEGORY_SUCCESS",
    GET_ALL_CATEGORY_FAILURE: "GET_ALL_CATEGORY_FAILURE",
    ADD_CATEGORY_REQUEST: "ADD_CATEGORY_REQUEST",
    ADD_CATEGORY_SUCCESS: "ADD_CATEGORY_SUCCESS",
    ADD_CATEGORY_FAILURE: "ADD_CATEGORY_FAILURE",
    UPDATE_CATEGORY_REQUEST: "UPDATE_CATEGORY_REQUEST",
    UPDATE_CATEGORY_SUCCESS: "UPDATE_CATEGORY_SUCCESS",
    UPDATE_CATEGORY_FAILURE: "UPDATE_CATEGORY_FAILURE",
    REMOVE_CATEGORY_REQUEST: "REMOVE_CATEGORY_REQUEST",
    REMOVE_CATEGORY_SUCCESS: "REMOVE_CATEGORY_SUCCESS",
    REMOVE_CATEGORY_FAILURE: "REMOVE_CATEGORY_FAILURE",
}

export const infoConstant = {
    GET_INFO_REQUEST: "GET_INFO_REQUEST",
    GET_INFO_SUCCESS: "GET_INFO_SUCCESS",
    GET_INFO_FAILURE: "GET_INFO_FAILURE",
    UPDATE_INFO_REQUEST: "UPDATE_INFO_REQUEST",
    UPDATE_INFO_SUCCESS: "UPDATE_INFO_SUCCESS",
    UPDATE_INFO_FAILURE: "UPDATE_INFO_FAILURE",
}